# 问题
* annotation
* ggmap
* 颜色梯度

```{r}
#install.packages("ggmap")
#install.packages("rjson")
library(ggmap)
load("Tsmall")
bjmap<-get_map(location="Beijing",zoom=10,source="google")
dim(bjmap)
BJggmap <- ggmap(bjmap,extent="device")
  BJggmap+
  geom_point(aes(x=lng,y=lat,colour=logscore,alpha=logscore),alpha=0.06,size=11,shape=15,data=Tsmall)+
  scale_colour_gradientn(colours=c('#77FF77','#00FF00','#77FF00','#FFFF00','yellow','red','red','purple'))+
  #ggtitle('2014-01-01 08')+
  #annotate("text",x=-Inf,y=Inf,label="2014-01-01 08",size=20)+
  #annotate("text",x=,y=,label="2014-01-01 08",size=20)+
  annotate("text",x=mean(range(Tsmall$lng)),y=mean(range(Tsmall$lat)),label="2014-01-01 08",colour="darkred",size=10)+
  theme(legend.position="none") # 去掉
```
# next
ggplot+stat_bin2d 
ggplot+stat_density2d
```{r}
library(ggmap)
load("Tsmall")
head(Tsmall)
bjmap<-get_map(location="Beijing",zoom=10,source="google")
BJggmap <- ggmap(bjmap,extent="device")
BJggmap
BJggmap+
  stat_density2d(geom="tile",aes(x=lng,y=lat,fill=..density..),contour=F,alpha=0.4,data=Tsmall)+
  scale_fill_gradientn(limits=c(0,7),colours=c('white','yellow','red'))+
  #scale_fill_gradient(limits=c(0,7),low="red",high="yellow")
  annotate("text",x=mean(range(Tsmall$lng)),y=mean(range(Tsmall$lat)),label="2014-01-01 08",colour="darkred",size=10)+
  theme(legend.position="none") # 去掉

#test
d=ggplot(Tsmall,aes(lng,lat))
d+stat_density2d(geom="tile",aes(fill=..density..),contour=F,alpha=0.5)+scale_fill_gradient(limits=c(0,7),low="red",high="yellow")
```

```{r}
d=ggplot(diamonds,aes(carat,price))+xlim(1,3)+theme(legend.position="none")
d+stat_bin2d(bins=100)
d+stat_bin2d(binwidth=c(0.02,200))
d+stat_binhex(bins=100)
d+stat_binhex(binwidth=c(0.02,200))
d+geom_point()+geom_density2d()
d+stat_density2d(geom="point",aes(size=..density..),contour=F)+scale_size_area()
d+stat_density2d(geom="tile",aes(fill=..density..),contour=F)
```

```{r}
d <- ggplot(diamonds, aes(carat, price))
d + stat_bin2d()
d + geom_bin2d()

# You can control the size of the bins by specifying the number of
# bins in each direction:
d + stat_bin2d(bins = 10)
d + stat_bin2d(bins = 30)

# Or by specifying the width of the bins
d + stat_bin2d(binwidth = c(1, 1000))
d + stat_bin2d(binwidth = c(.1, 500))

# Or with a list of breaks
x <- seq(min(diamonds$carat), max(diamonds$carat), by = 0.1)
y <- seq(min(diamonds$price), max(diamonds$price), length = 50)
d + stat_bin2d(breaks = list(x = x, y = y))

# With qplot
qplot(x, y, data = diamonds, geom="bin2d",
  xlim = c(4, 10), ylim = c(4, 10))
qplot(x, y, data = diamonds, geom="bin2d", binwidth = c(0.1, 0.1),
  xlim = c(4, 10), ylim = c(4, 10))
```
