# 用R的基础作图系统和ggplot2做常用图
这里我们会用R语言中的基础作图系统和ggplot2中的qplot以及ggplot作常见的图。
拨号下面几种常见的图：
* 散点图
* 线图
* 条形图
* 直方图,和密度图
* 箱线图
* 饼图
* 扇形图
常见的图形的代码都在下面的网站里。
http://docs.ggplot2.org/current/

## 数据集
某种动物的年龄和体长
```{r}
dugong=read.table("dugongs.txt",header=TRUE)
```

## ggplot2的安装,和载入
```{r}
#install.packages("ggplot2")
library(ggplot2)
```

## 散点图 
```{r}
plot(dugong$Age,dugong$Length,col="red")

#colour控制颜色
qplot(Age,Length,data=data,geom="point",colour="red")

qplot(data$Age,data$Length,geom="point",colour="red")

ggplot(data,aes(x=Age,y=Length))+geom_point()

```
# 线图
```{r}
plot(dugong$Age,dugong$Length,type="l")
# 在线上添加点
points(dugong$Age,dugong$Length)
dugong$Length1=dugong$Length*0.9
# 添加一条线
lines(dugong$Age,dugong$Length1,col="red")
points(dugong$Age,dugong$Length1)
# 添加平滑曲线
lines(spline(dugong$Age, dugong$Length, n = 201), col = 454, lwd = 2)
lines(spline(dugong$Age, dugong$Length1, n = 201), col = 454, lwd = 2)

qplot(Age,Length,data=data,geom="line")
qplot(Age,Length,data=data,geom=c("line","point"))
qplot(Age,Length,data=data,geom=c("line","point"))
qplot(Age,Length,data=data,geom=c("line","point","smooth"))



ggplot(data,aes(x=Age,y=Length))+geom_line()
ggplot(data,aes(x=Age,y=Length))+geom_line()+geom_point()+geom_smooth()

```
## 条形图
```{r}
dugong
# 显示27个Age
barplot(dugong$Age)
barplot(dugong$Length)
# ggplot的bar有所不同

```
## 直方图-核密度图
```{r}

```
## 箱线图
```{r}

```
## 饼图
```{r}

```
## 扇形图
```{r}

```